#routes pour notification    
notification:
    path:     /notification
    defaults: { _controller: "BZUserBundle:User:notification" }
    
contenu_user:
    path:     /contenu_user
    defaults: { _controller: "BZUserBundle:User:contenu_user" }

bz_user_changepassword:
    path:     /bz_user_changepassword
    defaults: { _controller: "BZUserBundle:ChangePassword:changePassword" }
    
bz_user_connecter:
    path:     /bz_user_connecter
    defaults: { _controller: "BZUserBundle:User:bz_user_connecter" }
    
bz_user_deck:
    path:     /bz_user_deck
    defaults: { _controller: "BZUserBundle:User:deconnecter" }
    
bz_user_profil:
    path:     /bz_user_profil/{id}
    defaults: { _controller: "BZUserBundle:User:bz_user_profil" }

bz_user_lock:
    path:     /bz_user_lock/{id}
    defaults: { _controller: "BZUserBundle:User:bz_user_lock" }
    
bz_user_unlock:
    path:     /bz_user_unlock/{id}
    defaults: { _controller: "BZUserBundle:User:bz_user_unlock" }
    #routes de login_check et login_out
fos_user_security_check:
    path:     /login_check
    defaults: { _controller: "BZUserBundle:User:fos_user_security_check" }
    
fos_user_security_logout:
    path:     /logout
    defaults: { _controller: "BZUserBundle:User:fos_user_security_logout" }
    #fin des routes
voir_groupe:
    pattern:    /voir_groupe
    defaults: { _controller: BZUserBundle:User:voir_groupe }