<?php

namespace BZ\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmetteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmetteurRepository extends EntityRepository
{
}
