<?php

namespace BZ\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
     public function getServices()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
                ->from('BZModelBundle:Service', 's')
                ->andWhere('s.estsupprimer =:supp')
                ->setParameter('supp', false);
        $qb->orderBy('s.denomination', 'ASC');
         return $qb->getQuery()
                ->getResult();
    }
    
    public function getServicesNotEmpty()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
                ->from('BZModelBundle:Service', 's');
//                ->where('u.estsupprimer =:param')
//                ->setParameter('param', false);
     return $qb;
    }
    
}
